version: "3.8"

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - ${OLLAMA_WEBAPI_PORT-11434}:11434
    volumes:
      - ollama:/root/.ollama
    extra_hosts:
      - host.docker.internal:host-gateway
  
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    pull_policy: always
    tty: true
    restart: unless-stopped
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_BASE_URL=http://host.docker.internal:${OLLAMA_WEBAPI_PORT-11434}
    extra_hosts:
      - host.docker.internal:host-gateway


volumes:
  ollama: {}
  open-webui: {}
